---
title: "class09 project"
author: "Benjamin Cho"
date: "April 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
wisc.df <- read.csv("WisconsinCancer.csv")
wisc.df

```

```{r}
wisc.data <- as.matrix(wisc.df[,3:32])
wisc.data
```

```{r}
row.names(wisc.data) <- wisc.df$id
head(wisc.data)
```

```{r}
#Q1. How many observations are in this dataset?
#Q2. How many variables/features in the data are suffixed with _mean?
colnames(wisc.data)
grep("_mean", colnames(wisc.data))
length(grep("_mean", colnames(wisc.data)))
#Q3. How many of the observations have a malignant diagnosis?
grep("1", diagnosis)
length(grep("1", diagnosis))
```


```{r}
diagnosis <- as.numeric(wisc.df$diagnosis == "M")
head(diagnosis)
```

```{r}
round( colMeans(wisc.data),1)
round( apply(wisc.data,2,sd),1)
```

```{r}
wisc.pr <- prcomp(wisc.data, scale=TRUE)
summary(wisc.pr)
```

```{r}
#Q4. From your results, what proportion of the original variance is captured by the first principal components (PC1)?
.4427
#Q5. How many principal components (PCs) are required to describe at least 70% of the original variance in the data?
3
#Q6. How many principal components (PCs) are required to describe at least 90% of the original variance in the data?
7
```




```{r}
biplot(wisc.pr)
```

```{r}
#Q7. What stands out to you about this plot? Is it easy or difficult to understand? Why?
#There's too much data and everything is jam packed. Most of them sway left for PC1

#scatterplot
```



```{r}
plot( wisc.pr$x[,1], wisc.pr$x[,2] , col = diagnosis+1 , 
     xlab = "PC1", ylab = "PC2")
```

```{r}
#Q8. Generate a similar plot for principal components 1 and 3. What do you notice about these plots?
#Looks like component 2 and 3 aren't correlated with malignant or benign
```



```{r}
plot( wisc.pr$x[,1], wisc.pr$x[,3] , col = diagnosis+1 , 
     xlab = "PC1", ylab = "PC2")
```

```{r}
pr.var <- round((wisc.pr$sdev^2),1)
pr.var
```

```{r}
pve <- pr.var/sum(pr.var)
pve
```

```{r}
plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```


```{r}
# Alternative scree plot of the same data, note data driven y-axis
barplot(pve, ylab = "Precent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
```

```{r}
pve2 <- cumsum(pve)
```

```{r}
plot(pve2, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```

```{r}
par(mfcol=c(1,2))
plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
plot(pve2, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```

```{r}
library(factoextra)
```

```{r}
fviz_eig(wisc.pr, addlabels = TRUE)
```


```{r}
data.scaled <- scale(wisc.data)
```

```{r}
data.dist <- dist(data.scaled)
```

```{r}
wisc.hclust <- hclust(data.dist, method="complete")
```

```{r}
plot(wisc.hclust)
abline(h=19, col = "red", lty=2)
```

```{r}
#Selecting number of clusters
```


```{r}
wisc.hclust.clusters <- cutree(wisc.hclust, k=4)
```

```{r}
table(wisc.hclust.clusters,diagnosis)
```

```{r}
#Using the minimum number of principal components required to describe at least 90% of the variability in the data, create a hierarchical clustering model with the linkage method="ward.D2". We use Ward’s criterion here because it is based on multidimensional variance like principal components analysis. Assign the results to wisc.pr.hclust.
```



```{r}
pr.dist <- dist(wisc.pr$x[,1:7])
wisc.pr.hclust <- hclust(pr.dist, method="ward.D2")
```


```{r}
plot(wisc.pr.hclust)
```

```{r}
grps <- cutree(wisc.pr.hclust, k=2)
table(grps)
```

```{r}
table(grps, diagnosis)
```

```{r}
plot(wisc.pr$x[,1:2], col=grps)
```

```{r}
plot(wisc.pr$x[,1:3], col=grps)
```



```{r}
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(wisc.pr, newdata=new)
npc
```

```{r}
plot(wisc.pr$x[,1:2], col=grps)
points(npc[,1], npc[,2], col="blue", pch=16)
```

